---
title: "Preguntas"
author: "Fabián Sepúlveda"
date: "12-10-2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Los datos
This data was collected (c. 2012) through on interactive online personality test. Participants were informed that their responses would be recorded and used for research at the begining of the test and asked to confirm their consent at the end of the test.

Estos datos fueron recolectado en un test de personalidad online. la informacion recolectada fue raza, edad, genero, ingles nativo (si son hablantes de ingles nativo) y se recolecta sus respuestas a las siguiente 50 preguntas en una escala de 5 puntos correspondientes a:

1=Disagree, 3=Neutral, 5=Agree (0=missed).

Las preguntas son las siguientes (en ingles)

E1	I am the life of the party.
E2	I don't talk a lot.
E3	I feel comfortable around people.
E4	I keep in the background.
E5	I start conversations.
E6	I have little to say.
E7	I talk to a lot of different people at parties.
E8	I don't like to draw attention to myself.
E9	I don't mind being the center of attention.
E10	I am quiet around strangers.
N1	I get stressed out easily.
N2	I am relaxed most of the time.
N3	I worry about things.
N4	I seldom feel blue.
N5	I am easily disturbed.
N6	I get upset easily.
N7	I change my mood a lot.
N8	I have frequent mood swings.
N9	I get irritated easily.
N10	I often feel blue.
A1	I feel little concern for others.
A2	I am interested in people.
A3	I insult people.
A4	I sympathize with others' feelings.
A5	I am not interested in other people's problems.
A6	I have a soft heart.
A7	I am not really interested in others.
A8	I take time out for others.
A9	I feel others' emotions.
A10	I make people feel at ease.
C1	I am always prepared.
C2	I leave my belongings around.
C3	I pay attention to details.
C4	I make a mess of things.
C5	I get chores done right away.
C6	I often forget to put things back in their proper place.
C7	I like order.
C8	I shirk my duties.
C9	I follow a schedule.
C10	I am exacting in my work.
O1	I have a rich vocabulary.
O2	I have difficulty understanding abstract ideas.
O3	I have a vivid imagination.
O4	I am not interested in abstract ideas.
O5	I have excellent ideas.
O6	I do not have a good imagination.
O7	I am quick to understand things.
O8	I use difficult words.
O9	I spend time reflecting on things.
O10	I am full of ideas.

# Posibles preguntas de investigación

* 1.-¿cual es la distribución demografica de los participantes?
* 2.-¿cual es la distribuciond de genero de las y los participantes?
* 3.-¿ cual es la distribucion de edades de las y los participantes?
* 4.-De las respuestas obtenidas ¿es posible identificar si las respuestas muestran factores comunes de personalidad?
* 5.-En caso de que la respuesta anterior sea positiva ¿afectara la distribucion de las preguntas 1 a 3 en la presencia de los factores de personalidad?

